"""Add receipt URL to expenses

Revision ID: 642f7df7f9d8
Revises: 9e8e4ba88ea4
Create Date: 2026-08-28 20:28:28.268652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642f7df7f9d8'
down_revision = '9e8e4ba88ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('receipt_url')

    # ### end Alembic commands ###
