"""add security questions to users

Revision ID: 9e8e4ba88ea4
Revises: b70fb1ad0311
Create Date: 2026-08-11 22:41:10.919737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8e4ba88ea4'
down_revision = 'b70fb1ad0311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_1_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_question_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_2_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_question_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_3_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer_3_hash')
        batch_op.drop_column('security_question_3')
        batch_op.drop_column('security_answer_2_hash')
        batch_op.drop_column('security_question_2')
        batch_op.drop_column('security_answer_1_hash')
        batch_op.drop_column('security_question_1')

    # ### end Alembic commands ###
